[Distribution]
Distribution=fedora

[Output]
ImageId=Ultramarine Linux
ManifestFormat=json
Output=%i_%v_%a
Format=disk
OutputDirectory=mkosi.output
OutputMode=777
SplitArtifacts=no


[Build]
WorkspaceDirectory=/var/cache/mkosi.workspace

[Content]
Packages=kernel
    bash
    systemd
    systemd-boot-unsigned
    dnf5
#RemovePackages=grub2-efi-x64 shim-x64
#Bootloader=systemd-boot
#BiosBootloader=grub
#Bootable=yes
# 
Autologin=yes
CleanPackageMetadata=no
# podman create $img
# podman mount $ctr
BaseTrees=/var/lib/containers/storage/overlay/77b4c9c27933c25c83cf89cbc4f7c3d0118e67fb66ac276672b34d8c8f285acb/merged
UnifiedKernelImages=no
RootPassword=root
# as much as i love mkosi-initrd we are still on dracut
MakeInitrd=no
## hack below
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=
## end hack


[Runtime]
Console=gui
RAM=4G
Firmware=uefi
Ephemeral=yes