[Distribution]
Distribution=fedora
Release=44

[Output]
ImageVersion=44
ImageId=Ultramarine-Stateful
ManifestFormat=json
Output=%i_%v_%a
Format=disk
OutputDirectory=mkosi.output
OutputMode=777
SplitArtifacts=no


[Build]
Incremental=yes
CacheDirectory=mkosi.cache

[Content]
Autologin=yes
CleanPackageMetadata=no
UnifiedKernelImages=no
RootPassword=root
## hack below
# as much as i love mkosi-initrd we are still on dracut
MakeInitrd=no
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=
## end hack


[Runtime]
RuntimeScratch=no
Console=gui
RAM=4G
Firmware=uefi