[Match]
Architecture=arm64

[Content]
Packages=rpi-update
         rpi-utils
         bcm283x-firmware
         bcm283x-overlays
         shim-unsigned-aarch64
         @arm-tools
[Build]
FinalizeScripts=arm.chroot