scripts:
  post:
    - id: cleanup
      name: Clean up system
      file: cleanup.sh
    - id: selinux-setup
      name: Set up SELinux
      file: selinux.sh
      chroot: false
      priority: 100
    - id: buildstamp
      name: Generate buildstamp
      file: buildstamp.sh

dnf:
  releasever: 40
  repodir: repodir
  options:
    - --setopt=cachedir=/var/cache/dnf
    - --setopt=keepcache=True
    - --setopt=tsflags=
    - --setopt=max_parallel_downloads=20
  exclude:
    - fedora-release*
    - generic-release*
    - kernel-debug*
    - setroubleshoot
    - setroubleshoot-plugins
    - setroubleshoot-server
  arch_packages:
    aarch64:
      - grub2-efi-aa64
      - grub2-efi-aa64-modules
      - grub2-efi-aa64-cdboot
      - shim-aa64
      - shim-unsigned-aarch64
      - bcm283x-firmware
      - bcm283x-overlays
      - "@arm-tools"
    x86_64:
      - grub2-efi-x64
      - grub2-efi-x64-modules
      - grub2-efi-x64-cdboot
      - grub2-pc
      - grub2-pc-modules
      - shim-x64
      - shim-unsigned-x64
  packages:
    - rpmfusion-free-release
    - rpmfusion-nonfree-release
    - rpmfusion-nonfree-release-tainted
    - rpmfusion-free-release-tainted
#   packages:
#     - filesystem
#     - setup
#     - lvm2
#     - btrfs-progs
#     - dmraid
#     - nvme-cli
#     - kernel
#     - kernel-devel
#     - kernel-modules
#     - kernel-core
#     - glibc
#     - glibc-common
#     - dracut-config-generic
#     - dracut-tools
#     - dnf
#     - dracut
#     - "@core"
#     - grub2-tools
#     - "@hardware-support"
#     - NetworkManager
#     - rpm
#     - libgomp
#     # - ultramarine-release-identity-basic
#     # - ultramarine-release-basic
#     - fedora-repos
#     - efibootmgr
#     - ultramarine-release-common
#     - ultramarine-release
#     - ultramarine-repos
#     - "ultramarine-logos*"

