name: Build Docker images
permissions:
  contents: read
env:
  KATSU_BUILD_TASK_NAME: "Build image"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
on:
  push:
    branches: ["um43"]
  workflow_dispatch:
  pull_request:
    branches: ["um43"]

jobs:
  #### DOCKER ######

  docker:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - base/base-docker-x86_64
          - base/base-docker-aarch64

    outputs:
      artifact: ${{ matrix.variant }}
      # ubuntu-latest unless we're building aarch64
    runs-on: ${{ endsWith(matrix.variant, '-aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/fyralabs/katsu:main
      # Pass /dev from host to container
      # Very hacky, but it works
      # Microsoft/Github, if you're reading this,
      # I'm sorry.
      options: --privileged -v /dev:/dev

    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: sanitize artifact name
        run: |
          name=$(echo ${{ matrix.variant }} | sed 's/\//-/g')

          # set github variable
          echo artifact=$name >> $GITHUB_ENV
          # get architecture
          # e.g. base/base-docker-x86_64 -> x86_64
          echo arch=$(echo ${{ matrix.variant }} | cut -d'-' -f3) >> $GITHUB_ENV
      - name: ${{ env.KATSU_BUILD_TASK_NAME }}
        run: |
          pushd katsu
          katsu --output=folder modules/${{ matrix.variant }}.yaml

          if [ ${{ env.arch }} == "x86_64" ]; then
            host_arch="amd64"
          elif [ ${{ env.arch }} == "aarch64" ]; then
            host_arch="arm64"
          fi

          # tarball katsu-work/chroot then import using podman with tag ghcr.io/ultramarine-linux/ultramarine:43
          tar -C katsu-work/chroot -c . | podman import --change='CMD ["/usr/bin/bash"]' - ghcr.io/ultramarine-linux/ultramarine:43 --arch $host_arch
          podman save --format oci-archive ghcr.io/ultramarine-linux/ultramarine:43 --output katsu-work/image/katsu.tar.xz
          popd

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ env.artifact }}-docker
          path: katsu/katsu-work/image/*.tar.xz
          compression-level: 0

      #### DOCKER PUSH ######

  docker-push:
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name != 'pull_request'

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # how do i combine those two images into one multiarch tag

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Publish to registry
        run: |
          set -x
          MANIFEST="ghcr.io/ultramarine-linux/ultramarine"
          RELEASE="43"
          ls -lR
          buildah manifest create $MANIFEST
          buildah manifest add $MANIFEST oci-archive:base-base-docker-x86_64-docker/katsu.tar.xz --arch amd64
          buildah manifest add $MANIFEST oci-archive:base-base-docker-aarch64-docker/katsu.tar.xz --arch arm64
          # also tag as latest
          buildah tag $MANIFEST $MANIFEST:latest || :
          buildah manifest push --all --format v2s2 $MANIFEST docker://$MANIFEST:$RELEASE

  docker-layer:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: docker-push
    strategy:
      fail-fast: true
      matrix:
        version:
          - 43
        docker:
          - dockerfile: dockerfiles/devtools.dockerfile
            image: ghcr.io/ultramarine-linux/ultramarine-devtools
          #- dockerfile: dockerfiles/gitpod.dockerfile
          # image: ghcr.io/ultramarine-linux/ultramarine-gitpod

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ${{ matrix.docker.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.docker.image }}:${{ matrix.version }}
            ${{ matrix.docker.image }}:latest
          build-args: |
            RELEASE=${{ matrix.version }}

  #### LIVE ISO ####
